import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://developmenti.ipswich.qld.gov.au/Home/ApplicationDetailsView?appNo=9%2F2022%2FSSPRV%2FS&type=plan_development_apps');
  await page.getByRole('heading', { name: 'Full Description:' }).click();
  await page.getByRole('heading', { name: 'Progress:' }).click();
  await page.getByRole('heading', { name: 'Stage/Decision:' }).click();
  await page.getByRole('heading', { name: 'Application Type:' }).click();
  await page.getByRole('heading', { name: 'Assessment Level:' }).click();
  await page.getByRole('heading', { name: 'Assessment Officer:' }).click();
  await page.getByRole('heading', { name: 'Date Submitted:' }).click();
  await page.getByRole('heading', { name: 'Public Notification Required:' }).click();
  await page.getByRole('heading', { name: 'Associated Properties   ' }).click();
  await page.goto('https://developmenti.ipswich.qld.gov.au/Home/ApplicationDetailsView?appNo=5125%2F2021%2FMAMC%2FA&type=plan_development_apps');
  await page.getByRole('heading', { name: 'Full Description:' }).click();
  await page.getByRole('heading', { name: 'Progress:' }).click();
  await page.locator('div').filter({ hasText: /^Stage\/Decision:$/ }).click();
  await page.getByRole('heading', { name: 'Application Type:' }).click();
  await page.getByRole('heading', { name: 'Assessment Level:' }).click();
  await page.getByRole('heading', { name: 'Use:' }).click();
  await page.getByRole('heading', { name: 'Assessment Officer:' }).click();
  await page.getByRole('heading', { name: 'Date Submitted:' }).click();
  await page.getByRole('heading', { name: 'Public Notification Required:' }).click();
  await page.goto('https://developmenti.ipswich.qld.gov.au/Home/ApplicationDetailsView?appNo=4642%2F2021%2FOW&type=plan_development_apps');
  await page.locator('div').filter({ hasText: /^Full Description:$/ }).click();
  await page.getByRole('heading', { name: 'Progress:' }).click();
  await page.getByRole('heading', { name: 'Stage/Decision:' }).click();
  await page.getByRole('heading', { name: 'Application Type:' }).click();
  await page.getByRole('heading', { name: 'Assessment Level:' }).click();
  await page.getByRole('heading', { name: 'Use:' }).click();
  await page.getByRole('heading', { name: 'Assessment Officer:' }).click();
  await page.getByRole('heading', { name: 'Date Submitted:' }).click();
  await page.getByRole('heading', { name: 'Date Decided:' }).click();
  await page.getByRole('heading', { name: 'Public Notification Required:' }).click();
});